controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

api_controllers:
    resource: ../../src/Controller/Api
    type: annotation
    prefix: '/api'

api_admin_controllers:
    resource: ../../src/Controller/Api/Admin
    type: annotation
    prefix: '/api/admin'
